[project]
name = "cashflow-financial-planner"
version = "1.0.0"
description = "Cash Flow Financial Planner for fashion supply chain"

dependencies = [
    "uagents>=0.12.0",
    "uagents-core>=0.2.0"
]
