[project]
name = "production-timeline-manager"
version = "1.0.0"
description = "Production Timeline Manager for fashion supply chain"

dependencies = [
    "uagents>=0.12.0",
    "uagents-core>=0.2.0"
]
