[project]
name = "inventory-demand-forecaster"
version = "1.0.0"
description = "Inventory & Demand Forecaster for fashion supply chain"

dependencies = [
    "uagents>=0.12.0",
    "uagents-core>=0.2.0"
]
